### PR TITLE
Pull request for code review

### PR DESCRIPTION
**Pull request by frederico-miranda**
This is a pull request opened for receiving a code review. This project is big and I would like to know  how much is actually required for this to be validated (before I can continue working on it further).

Link to a live version of the page:
https://cdn.statically.io/gh/frederico-miranda/using-bootstrap/main-development/index.html

### CODE REVIEW

**Comment by frederico-miranda** [comment]
This pull request needs an update so that the stickler check can be run.

**Comment by shshamim63** [comment]
## Status :arrow_right:  [Required Changes] :arrow_left: 
___
Hi @frederico-miranda :wave: ,
Well you have most of the content in your project. That is a great achievement :clap:. I agree with you that it is a tricky and a little big project. So it is normal to raise a question that `How much is enough to validate this project as complete?`. Well i can say one line `The more you can come closer to the original one you are near to success.` In short I can provide you some tips on how you can break this project in separate parts.
___
1. First of all stickler must be functional.
2. Project should be responsive to the devices.
3. Code should be clean and without basic CSS bad practices.
___
:fire:  Now what should your project contain?
### [Navbar]
It contains Newsweek logo with current date. Sign in and Subscribe links and navigation links. 
### [Main content]
Well it should contain all the section that are visible on the actual webpage, but you are allowed to repeat data that are similar. The main task is to control the flow of the content
### [Footer]
It is decorated with Newsweek logo, social media icons and main navigation links.

#### Again it should be responsive.
___
I hope, this will help you to move forward on this project. If you need more info don't hesitate to knock me.
___
## Happy Coding :clubs: 
### Shakhawat Hossain
[Linkedin](https://www.linkedin.com/in/shakhawat-hossain-7750b0127/) | [Slack](Shakhawat Hossain)

**Comment by frederico-miranda** [comment]
@shshamim63 , @ebukaume

Hi, code reviewers. I initially asked about the size of the scope of this project because the Newsweek website has effects that I thought that could be implemented using bootstrap alone (I'm very new to bootstrap, I haven't used it before this project), like the hamburger button that collapses the vertical navigator bar as it is pressed ([image #1](https://ibb.co/2sCPK8h), [image #2](https://ibb.co/bgK9bv3)) and a fixed banner that only appears after the ```window.visualViewport.pageTop```  has reached a certain value ([image #3](https://ibb.co/vLXZ9Y9), [image #4](https://ibb.co/CVVcRPm)). I have looked through the bootstrap documentation and, though I have found things similar to that ([bootstrap collapse button](https://getbootstrap.com/docs/4.0/components/collapse/)), I believe so far this is not possible with bootstrap alone. If these features of the website were a must on the project, I thought of implementing them with JavaScript, but I was worried about possibly wasting a non-trivial amount of time by having the implementation of these features rejected because they're not using bootstrap but a hand-crafted script (In simpler words, it would look like I'm cheating).

I've implemented the required changes.

**Comment by ebukaume** [comment]
> @shshamim63 , @ebukaume
> 
> Hi, code reviewers. I initially asked about the size of the scope of this project because the Newsweek website has effects that I thought that could be implemented using bootstrap alone (I'm very new to bootstrap, I haven't used it before this project), like the hamburger button that collapses the vertical navigator bar as it is pressed ([image #1](https://ibb.co/2sCPK8h), [image #2](https://ibb.co/bgK9bv3)) and a fixed banner that only appears after the `window.visualViewport.pageTop` has reached a certain value ([image #3](https://ibb.co/vLXZ9Y9), [image #4](https://ibb.co/CVVcRPm)). I have looked through the bootstrap documentation and, though I have found things similar to that ([bootstrap collapse button](https://getbootstrap.com/docs/4.0/components/collapse/)), I believe so far this is not possible with bootstrap alone. If these features of the website were a must on the project, I thought of implementing them with JavaScript, but I was worried about possibly wasting a non-trivial amount of time by having the implementation of these features rejected because they're not using bootstrap but a hand-crafted script (In simpler words, it would look like I'm cheating).
> 
> I've implemented the required changes.

Hi @frederico-miranda,

Those are not within the scope of this project. But they can be achieved using JavaScript. Specifically, the collapse effect can be achieved with bootstrap, but it requires you link to a javascript dependency (popper.js). Read [this](https://getbootstrap.com/docs/4.3/components/navbar/#how-it-works).

**Pull request merged**
